---
# tasks form myvhost

- name: install httpd
  yum:
    name: httpd
    state: latest

- name: start the service and enable
  service:
    name: httpd
    state: started
    enabled: true

- name: deliver the html content
  copy:
    src: html/
    dest: "/var/www/vhosts/{{ ansible_hostname }}"

- name: push template with httpd conf
  template:
    src: vhost.conf.j2
    dest: /etc/httpd/conf.d/vhost.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart httpd
