---
- hosts: all
  become: yes
  tasks:
    - name: get the hosname details
      debug:
        msg: >
            the default ip4 address of  {{ ansible_fqdn }} is {{ ansible_default_ipv4.address }}
            {{ ansible_architecture }}
