---
- name: install pkgs with vars
  hosts: client
  become: yes
  tasks:
    - name: install httpd pkgs with output result
      yum:
        name: httpd
        state: installed
      register: install_result
    - debug: var=install_result
